### ISSUE TITLE
Website down

### ISSUE THREAD

**Issue by AndreasNasman** [ThePrimeagen/vim-fundamentals#1]
Hi!

The website for this repo seems to be down:
https://theprimeagen.github.io/vim-fundamentals/

I'm currently taking the corresponding master class on Frontend Masters and it would be nice to have the website live! 😄

Thanks,
– Andreas

**Comment by ThePrimeagen** [comment]
I am so sorry!  I don't know how gatsby works and I am trying to get the next course up and running.  I'll try to get this up and running as quickly as possible. 

I am truly sorry about this.

**Comment by ThePrimeagen** [comment]
Website up

**Comment by AndreasNasman** [comment]
No worries! Thanks for the quick fix! 👍
